name: build and publish
"on":
  workflow_dispatch: {}
  push:
    tags: ["v*"]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the source code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: "go.mod"

      - name: cache go modules
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9

      - name: build and push container images
        run: ./hack/build.sh
        env:
          KO_PUSH: "true"
          KO_DOCKER_REPO: "ghcr.io/${{ github.repository }}"

      - name: generate a build timestamp and sha256sum files
        run: |
          cd builds
          echo `date -u +'%Y%m%d%H%M%S'` > ./build_timestamp.txt
          echo `date -u +'%Y-%m-%dT%H:%M:%S%:z'` >> ./build_timestamp.txt
          sha256sum *.yaml > ./SHA256SUMS.txt

      - name: update release notes and executables
        if: startsWith(github.ref, 'refs/tags/') # executes only for new release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            builds/*.yaml
            builds/build_timestamp.txt
            builds/SHA256SUMS.txt

      - name: Update executables for main branch changes
        if: startsWith(github.ref, 'refs/heads/main') # executes only for changes in main
        uses: marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1 # latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: main-devel
          prerelease: true
          title: "Development Build - main branch"
          files: |
            builds/*.yaml
            builds/build_timestamp.txt
            builds/SHA256SUMS.txt
